version: "3"

services:
  linter-service:
    image: unjudge/linter-web-service
    ports:
      - "${LINTER_PORT}:4567"
    restart: always
  python-tutor:
    image: unjudge/onlinepythontutor
    ports:
      - "${PYTHON_TUTOR_PORT}:8003"
    restart: always
  cokapi:
    image: unjudge/cokapi
    ports:
      - "${COKAPI_PORT}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  database-service:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    volumes: inginious-data:/data/db
